# Generated by Django 3.2.6 on 2022-03-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220330_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ad',
        ),
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.ad'),
        ),
    ]
