# Generated by Django 3.2.6 on 2022-04-01 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20220330_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(help_text='Подробное описание товара товара', max_length=1000, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Вставьте фото товара', null=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Цена товара (только цифры)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Краткое название товара', max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название товара'),
        ),
    ]
